package sop_corba_notificacion;


/**
* sop_corba_notificacion/INotificationControllerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:02 PM COT
*/

abstract public class INotificationControllerHelper
{
  private static String  _id = "IDL:sop_corba_notificacion/INotificationController:1.0";

  public static void insert (org.omg.CORBA.Any a, sop_corba_notificacion.INotificationController that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static sop_corba_notificacion.INotificationController extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (sop_corba_notificacion.INotificationControllerHelper.id (), "INotificationController");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static sop_corba_notificacion.INotificationController read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_INotificationControllerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, sop_corba_notificacion.INotificationController value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static sop_corba_notificacion.INotificationController narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba_notificacion.INotificationController)
      return (sop_corba_notificacion.INotificationController)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba_notificacion._INotificationControllerStub stub = new sop_corba_notificacion._INotificationControllerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static sop_corba_notificacion.INotificationController unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof sop_corba_notificacion.INotificationController)
      return (sop_corba_notificacion.INotificationController)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      sop_corba_notificacion._INotificationControllerStub stub = new sop_corba_notificacion._INotificationControllerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
