package sop_corba_notificacion;

/**
* sop_corba_notificacion/INotificationControllerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:02 PM COT
*/

public final class INotificationControllerHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_notificacion.INotificationController value = null;

  public INotificationControllerHolder ()
  {
  }

  public INotificationControllerHolder (sop_corba_notificacion.INotificationController initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_notificacion.INotificationControllerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_notificacion.INotificationControllerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_notificacion.INotificationControllerHelper.type ();
  }

}
