package sop_corba_notificacion.INotificationControllerPackage;


/**
* sop_corba_notificacion/INotificationControllerPackage/NotificationDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:03 PM COT
*/

public final class NotificationDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String nombre = null;
  public String apellido = null;
  public int edad = (int)0;
  public float color = (float)0;
  public String fecha = null;

  public NotificationDTO ()
  {
  } // ctor

  public NotificationDTO (int _id, String _nombre, String _apellido, int _edad, float _color, String _fecha)
  {
    id = _id;
    nombre = _nombre;
    apellido = _apellido;
    edad = _edad;
    color = _color;
    fecha = _fecha;
  } // ctor

} // class NotificationDTO
