package sop_corba_notificacion.INotificationControllerPackage;


/**
* sop_corba_notificacion/INotificationControllerPackage/LstNotificationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:03 PM COT
*/

public final class LstNotificationHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba_notificacion.INotificationControllerPackage.NotificationDTO value[] = null;

  public LstNotificationHolder ()
  {
  }

  public LstNotificationHolder (sop_corba_notificacion.INotificationControllerPackage.NotificationDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba_notificacion.INotificationControllerPackage.LstNotificationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba_notificacion.INotificationControllerPackage.LstNotificationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba_notificacion.INotificationControllerPackage.LstNotificationHelper.type ();
  }

}
