package sop_corba.IStudentControllerPackage;


/**
* sop_corba/IStudentControllerPackage/InformeDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 8 de agosto de 2022 11:58:25 AM COT
*/

public final class InformeDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int alertasRojas = (int)0;
  public int estudiantesBienestar[] = null;
  public int alertaVerdeCorte[] = null;

  public InformeDTO ()
  {
  } // ctor

  public InformeDTO (int _alertasRojas, int[] _estudiantesBienestar, int[] _alertaVerdeCorte)
  {
    alertasRojas = _alertasRojas;
    estudiantesBienestar = _estudiantesBienestar;
    alertaVerdeCorte = _alertaVerdeCorte;
  } // ctor

} // class InformeDTO
