package sop_corba.IStudentControllerPackage;


/**
* sop_corba/IStudentControllerPackage/InformeDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 03:07:52 PM COT
*/

public final class InformeDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int alertasRojas = (int)0;
  public int estudiantesBienestar = (int)0;
  public int alertaVerdeCorte[] = null;

  public InformeDTO ()
  {
  } // ctor

  public InformeDTO (int _alertasRojas, int _estudiantesBienestar, int[] _alertaVerdeCorte)
  {
    alertasRojas = _alertasRojas;
    estudiantesBienestar = _estudiantesBienestar;
    alertaVerdeCorte = _alertaVerdeCorte;
  } // ctor

} // class InformeDTO
