package sop_corba.IStudentControllerPackage;


/**
* sop_corba/IStudentControllerPackage/LstStudentHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 03:07:52 PM COT
*/

public final class LstStudentHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.IStudentControllerPackage.StudentDTO value[] = null;

  public LstStudentHolder ()
  {
  }

  public LstStudentHolder (sop_corba.IStudentControllerPackage.StudentDTO[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.IStudentControllerPackage.LstStudentHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.IStudentControllerPackage.LstStudentHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.IStudentControllerPackage.LstStudentHelper.type ();
  }

}
