package sop_corba.IStudentControllerPackage;

/**
* sop_corba/IStudentControllerPackage/StudentDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 8 de agosto de 2022 11:58:25 AM COT
*/

public final class StudentDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public sop_corba.IStudentControllerPackage.StudentDTO value = null;

  public StudentDTOHolder ()
  {
  }

  public StudentDTOHolder (sop_corba.IStudentControllerPackage.StudentDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sop_corba.IStudentControllerPackage.StudentDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sop_corba.IStudentControllerPackage.StudentDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sop_corba.IStudentControllerPackage.StudentDTOHelper.type ();
  }

}
