package sop_corba_notificacion;


/**
* sop_corba_notificacion/_INotificationControllerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:02 PM COT
*/

public class _INotificationControllerStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba_notificacion.INotificationController
{

  public sop_corba_notificacion.INotificationControllerPackage.NotificationDTO[] findAllNotifications ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findAllNotifications", true);
                $in = _invoke ($out);
                sop_corba_notificacion.INotificationControllerPackage.NotificationDTO $result[] = sop_corba_notificacion.INotificationControllerPackage.LstNotificationHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findAllNotifications (        );
            } finally {
                _releaseReply ($in);
            }
  } // findAllNotifications

  public boolean registrarNotification (sop_corba_notificacion.INotificationControllerPackage.NotificationDTO save)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarNotification", true);
                sop_corba_notificacion.INotificationControllerPackage.NotificationDTOHelper.write ($out, save);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarNotification (save        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarNotification

  public sop_corba_notificacion.INotificationControllerPackage.NotificationDTO[] findNotificationByStudentId (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findNotificationByStudentId", true);
                $out.write_long (id);
                $in = _invoke ($out);
                sop_corba_notificacion.INotificationControllerPackage.NotificationDTO $result[] = sop_corba_notificacion.INotificationControllerPackage.LstNotificationHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findNotificationByStudentId (id        );
            } finally {
                _releaseReply ($in);
            }
  } // findNotificationByStudentId

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba_notificacion/INotificationController:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _INotificationControllerStub
