package sop_corba_notificacion;


/**
* sop_corba_notificacion/INotificationControllerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:03 PM COT
*/

public interface INotificationControllerOperations 
{
  sop_corba_notificacion.INotificationControllerPackage.NotificationDTO[] findAllNotifications ();
  boolean registrarNotification (sop_corba_notificacion.INotificationControllerPackage.NotificationDTO save);
  sop_corba_notificacion.INotificationControllerPackage.NotificationDTO[] findNotificationByStudentId (int id);
} // interface INotificationControllerOperations
