package sop_corba_notificacion;


/**
* sop_corba_notificacion/INotificationController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* sábado 6 de agosto de 2022 06:46:02 PM COT
*/

public interface INotificationController extends INotificationControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface INotificationController
