package sop_corba;


/**
* sop_corba/_IStudentControllerStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* lunes 8 de agosto de 2022 11:58:25 AM COT
*/

public class _IStudentControllerStub extends org.omg.CORBA.portable.ObjectImpl implements sop_corba.IStudentController
{

  public sop_corba.IStudentControllerPackage.StudentDTO[] findAllStudent ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findAllStudent", true);
                $in = _invoke ($out);
                sop_corba.IStudentControllerPackage.StudentDTO $result[] = sop_corba.IStudentControllerPackage.LstStudentHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findAllStudent (        );
            } finally {
                _releaseReply ($in);
            }
  } // findAllStudent

  public boolean registrarNota (sop_corba.IStudentControllerPackage.StudentDTO save)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("registrarNota", true);
                sop_corba.IStudentControllerPackage.StudentDTOHelper.write ($out, save);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return registrarNota (save        );
            } finally {
                _releaseReply ($in);
            }
  } // registrarNota

  public sop_corba.IStudentControllerPackage.StudentDTO findStudentById (int id)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findStudentById", true);
                $out.write_long (id);
                $in = _invoke ($out);
                sop_corba.IStudentControllerPackage.StudentDTO $result = sop_corba.IStudentControllerPackage.StudentDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findStudentById (id        );
            } finally {
                _releaseReply ($in);
            }
  } // findStudentById

  public sop_corba.IStudentControllerPackage.InformeDTO generarInforme ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("generarInforme", true);
                $in = _invoke ($out);
                sop_corba.IStudentControllerPackage.InformeDTO $result = sop_corba.IStudentControllerPackage.InformeDTOHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return generarInforme (        );
            } finally {
                _releaseReply ($in);
            }
  } // generarInforme

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:sop_corba/IStudentController:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _IStudentControllerStub
