package sop_corba;


/**
* sop_corba/IStudentController.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from interface.idl
* viernes 5 de agosto de 2022 03:07:52 PM COT
*/

public interface IStudentController extends IStudentControllerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IStudentController
